In [4]:
import pandas as pd

air_data = pd.read_csv('CIVE202_Spring2026_Project1_AirData.csv')

air_data = pd.DataFrame(air_data)

In [5]:
air_data_grouped = air_data.groupby(['sensor.name'])

mean_air_data_aggregated_pm_2_5 = air_data_grouped.agg(mean_pm_2_5 = ('pm2.5_atm', 'mean'))
                                               
                                                 
top5_mean_pm_2_5 = (
    mean_air_data_aggregated_pm_2_5
    .sort_values(by = 'mean_pm_2_5', ascending = False)
    .head(5))



top5_mean_pm_2_5

                                                    mean_pm_2_5
sensor.name
Broken Bow                                           928.710593
#16 - Richardson County Courthouse                   700.127342
#18 - Southeast District Health Department- Tec...   613.175352
NCDHD O'Neill #11                                    164.495078
Swnphd-mccook                                        123.011622

In [83]:
median_air_data_aggregated_pm_2_5 = air_data_grouped.agg(median_pm_2_5 = ('pm2.5_atm', 'median'))
                                               
                                                 
top5_median_pm_2_5 = (
    median_air_data_aggregated_pm_2_5
    .sort_values(by = 'median_pm_2_5', ascending = False)
    .head(5))



top5_median_pm_2_5

                                                    median_pm_2_5
sensor.name
Broken Bow                                              36.050240
#16 - Richardson County Courthouse                      11.977344
#18 - Southeast District Health Department- Tec...      10.322875
ELVPHD Norfolk HD 4                                      9.706229
ELVPHD Wisner HD 5                                       8.464583

In [84]:
mean_air_data_aggregated_pm_10_0 = air_data_grouped.agg(mean_pm_10_0 = ('pm10.0_atm', 'mean'))
                                               
                                                 
top5_mean_pm_10_0 = (
    mean_air_data_aggregated_pm_10_0
    .sort_values(by = 'mean_pm_10_0', ascending = False)
    .head(5))



top5_mean_pm_10_0

                                                    mean_pm_10_0
sensor.name
Broken Bow                                            929.678512
#16 - Richardson County Courthouse                    701.632446
#18 - Southeast District Health Department- Tec...    614.227248
NCDHD O'Neill #11                                     166.132578
Swnphd-mccook                                         124.227336

In [22]:
median_air_data_aggregated_pm_10_0 = air_data_grouped.agg(median_pm_10_0 = ('pm10.0_atm', 'median'))
                                               
                                                 
top5_median_pm_10_0 = (
    median_air_data_aggregated_pm_10_0
    .sort_values(by = 'median_pm_10_0', ascending = False)
    .head(5))



top5_median_pm_10_0

                                                    median_pm_10_0
sensor.name
Broken Bow                                               43.179094
#16 - Richardson County Courthouse                       13.305615
ELVPHD Norfolk HD 4                                      11.474708
#18 - Southeast District Health Department- Tec...       11.433729
ELVPHD Wisner HD 5                                       10.935958

In [25]:
mean_air_data_aggregated_voc = air_data_grouped.agg(mean_voc = ('voc', 'mean'))
                                               
                                                 
top5_mean_voc = (
    mean_air_data_aggregated_voc
    .sort_values(by = 'mean_voc', ascending = False)
    .head(5))



top5_mean_voc

                                         mean_voc
sensor.name
Swnphd-ogallala                        399.434240
FCHD-YPS                               372.462720
Three Rivers Public Health Department  370.216208
ELVPHD Norfolk HD 4                    360.833744
Swnphd-mccook                          353.941581

In [93]:
median_air_data_aggregated_voc = air_data_grouped.agg(median_voc = ('voc', 'median'))

top5_median_voc = (
    median_air_data_aggregated_voc
    .sort_values(by = 'median_voc', ascending = False)
    .head(5))

top5_median_voc

                                       median_voc
sensor.name
Swnphd-ogallala                        423.082292
Swnphd-mccook                          381.468479
Three Rivers Public Health Department  376.810167
FCHD-YPS                               375.383500
ELVPHD Norfolk HD 4                    368.580500

In [160]:
unhealthy_voc = air_data[air_data['voc'] > 0]

unhealthy_events_voc = unhealthy_voc[
    ['date', 'sensor.name', 'humidity', 'temperature', 'voc']].sort_values('voc')

unhealthy_events_voc.tail(5)

            date          sensor.name   humidity  temperature          voc
5024  10/16/2024       SWNPHD-Imerial  16.784000    72.183000   871.182000
4948  10/12/2024  ELVPHD Norfolk HD 4  29.733500    77.483000   884.649000
5774  11/23/2024       SWNPHD-Imerial  43.071000    53.487000  1041.722000
4795   10/5/2024       SWNPHD-Imerial  26.333000    80.292000  1135.473000
2391   6/24/2024      Swnphd-ogallala   9.883429   116.455286  1209.931571

In [158]:
pm_2_5high = air_data[air_data['pm2.5_atm'] > 0]

pm_2_5high_events = pm_2_5high[
    ['date', 'sensor.name', 'pm2.5_atm']].sort_values('pm2.5_atm')

pm_2_5high_events.tail(5)

           date                         sensor.name    pm2.5_atm
7572  2/18/2025                          Broken Bow  3205.868854
6962  1/21/2025  #16 - Richardson County Courthouse  3209.817146
7605  2/20/2025  #16 - Richardson County Courthouse  3243.746646
7583  2/19/2025  #16 - Richardson County Courthouse  3401.999333
7561  2/18/2025  #16 - Richardson County Courthouse  3782.823313

In [147]:
pm_10high = air_data[air_data['pm10.0_atm'] > 0]

pm_10high_events = pm_10high[
    ['date', 'sensor.name', 'pm10.0_atm']].sort_values('pm10.0_atm')

pm_10high_events.tail(5)

           date                         sensor.name   pm10.0_atm
7572  2/18/2025                          Broken Bow  3206.779708
6962  1/21/2025  #16 - Richardson County Courthouse  3211.046813
7605  2/20/2025  #16 - Richardson County Courthouse  3245.613354
7583  2/19/2025  #16 - Richardson County Courthouse  3403.435958
7561  2/18/2025  #16 - Richardson County Courthouse  3784.682542

In [154]:
def assign_humidity(humidity):
    if humidity < 50 :
        return 'Low'
    elif 50 <= humidity <= 80:
        return 'High'
    elif humidity > 81: 
        return 'Very High'
    else:
        return '-'

air_data['humidity_level'] = air_data['humidity'].apply(assign_humidity)

air_data

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,humidity_level
0,2/23/2024,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
1,2/23/2024,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Low
2,2/23/2024,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Low
3,2/24/2024,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
4,2/24/2024,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,3/24/2025,195373,23.636208,915.998292,61.489083,421.493750,0.020000,0.762500,0.486583,0.830021,1.416125,41.148170,-100.761800,2800,WCDHD City Building,Low
8297,3/24/2025,195379,28.043545,954.294546,66.009182,301.074800,0.000000,0.800000,5.625545,5.873364,6.056773,40.877007,-97.579445,1639,FCHD-YPS,Low
8298,3/24/2025,195383,31.451375,936.556583,55.752792,353.478000,0.050000,0.575000,0.267500,0.478375,0.818146,41.779380,-99.138040,2174,Loup Basin Public Health Department,Low
8299,3/24/2025,195385,NaN,NaN,NaN,NaN,0.010000,0.970833,0.739500,1.088604,1.340563,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,-
8300,3/24/2025,195541,20.494500,901.484750,61.222167,485.556417,0.020000,0.554167,0.132083,0.340417,0.737375,41.128284,-101.720220,3220,Swnphd-ogallala,Low

In [155]:
def assign_temperature(temperature):
    if temperature < 32 :
        return 'Below Freezing'
    elif 32 <= temperature <= 50:
        return 'Cool'
    elif 51 <= temperature <= 70:
        return 'Warm'
    elif temperature > 70:
        return 'Hot'
    else:
        return '-'

air_data['temperature_level'] = air_data['temperature'].apply(assign_temperature)

air_data

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,humidity_level,temperature_level
0,2/23/2024,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Low,Warm
1,2/23/2024,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Low,Hot
2,2/23/2024,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Low,Warm
3,2/24/2024,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Low,Warm
4,2/24/2024,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Low,Warm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,3/24/2025,195373,23.636208,915.998292,61.489083,421.493750,0.020000,0.762500,0.486583,0.830021,1.416125,41.148170,-100.761800,2800,WCDHD City Building,Low,Warm
8297,3/24/2025,195379,28.043545,954.294546,66.009182,301.074800,0.000000,0.800000,5.625545,5.873364,6.056773,40.877007,-97.579445,1639,FCHD-YPS,Low,Warm
8298,3/24/2025,195383,31.451375,936.556583,55.752792,353.478000,0.050000,0.575000,0.267500,0.478375,0.818146,41.779380,-99.138040,2174,Loup Basin Public Health Department,Low,Warm
8299,3/24/2025,195385,NaN,NaN,NaN,NaN,0.010000,0.970833,0.739500,1.088604,1.340563,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,-,-
8300,3/24/2025,195541,20.494500,901.484750,61.222167,485.556417,0.020000,0.554167,0.132083,0.340417,0.737375,41.128284,-101.720220,3220,Swnphd-ogallala,Low,Warm

In [150]:
unhealthy_pm_10 = air_data[air_data['pm10.0_atm'] > 155]

unhealthy_events_pm10 = unhealthy_pm_10[
    ['date', 'sensor.name', 'pm10.0_atm']].sort_values('pm10.0_atm')

unhealthy_events_pm10

           date                          sensor.name   pm10.0_atm
2443  6/27/2024                     Swnphd-Benklemen   188.977500
6076  12/8/2024   #16 - Richardson County Courthouse   200.798396
2144  6/14/2024  Loup Basin Public Health Department   231.757021
5996  12/4/2024   #16 - Richardson County Courthouse   261.677250
4684  9/29/2024                           Broken Bow   264.340688
...         ...                                  ...          ...
7572  2/18/2025                           Broken Bow  3206.779708
6962  1/21/2025   #16 - Richardson County Courthouse  3211.046813
7605  2/20/2025   #16 - Richardson County Courthouse  3245.613354
7583  2/19/2025   #16 - Richardson County Courthouse  3403.435958
7561  2/18/2025   #16 - Richardson County Courthouse  3784.682542

[391 rows x 3 columns]

In [157]:
unhealthy_pm_2_5 = air_data[air_data['pm2.5_atm'] > 35.5]

unhealthy_events_pm2_5 = unhealthy_pm_2_5[
    ['date', 'sensor.name', 'pm2.5_atm' ]].sort_values('pm2.5_atm')

unhealthy_events_pm2_5

,date,sensor.name,pm2.5_atm
1357,5/14/2024,Broken Bow,35.501729
3208,7/27/2024,Loup Basin Public Health Department,35.529521
3799,8/21/2024,South Heartland District Health Dept. Hastings...,35.675229
7836,3/2/2025,Swnphd-mccook,35.738500
6720,1/9/2025,#17 - Otoe County,35.746292
...,...,...,...
7572,2/18/2025,Broken Bow,3205.868854
6962,1/21/2025,#16 - Richardson County Courthouse,3209.817146
7605,2/20/2025,#16 - Richardson County Courthouse,3243.746646
7583,2/19/2025,#16 - Richardson County Courthouse,3401.999333
7561,2/18/2025,#16 - Richardson County Courthouse,3782.823313